linters-settings:
  golint:
    min-confidence: 1
  gocyclo:
    min-complexity: 20
  maligned:
    suggest-new: true
  dupl:
    threshold: 100
  goconst:
    min-len: 2
    min-occurrences: 2
  misspell:
    locale: US
  funlen:
    lines: 200
    statements: 40
  gocognit:
    min-complexity: 40

linters:
  enable-all: true
  disable:
    - typecheck
    - megacheck
    - wsl
