# In this directory, run the following command to di this builder.
# $ gcloud builds submit . --config=cloudbuild.yaml

steps:
  # Start CI process.
  - name: 'gcr.io/mono-264416/go-ci'
    args: ['make', 'ci']