# In this directory, run the following command to build this builder.
# $ gcloud builds submit . --config=cloudbuild.yaml


steps:
  # Start CI process.
  - name: 'stiks/go-lint-dep'
    args: ['make', 'test']